kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- profile-volumes.yaml
- github.com/pingidentity/pingidentity-devops-getting-started/20-kubernetes/01-standalone/pingfederate
- github.com/pingidentity/pingidentity-devops-getting-started/20-kubernetes/01-standalone/pingdataconsole
- github.com/pingidentity/pingidentity-devops-getting-started/20-kubernetes/01-standalone/pingdirectory
- github.com/pingidentity/pingidentity-devops-getting-started/20-kubernetes/01-standalone/pingaccess

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: pingdataconsole
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 200m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 200m
  - target:
      group: 
      version: v1
      kind: Service
      name: pingdirectory-cluster
    patch: |-
      - op: remove
        path: /spec/clusterIP
      - op: add
        path: /spec/type
        value: NodePort
  - target:
      group: 
      version: v1
      kind: Service
      name: pingfederate
    patch: |-
      - op: add
        path: /spec/type
        value: NodePort
  - target:
      group: 
      version: v1
      kind: Service
      name: pingdataconsole
    patch: |-
      - op: add
        path: /spec/type
        value: NodePort
  - target:
      group: 
      version: v1
      kind: Service
      name: pingaccess
    patch: |-
      - op: add
        path: /spec/type
        value: NodePort
  # Remove entries for profile URL and paths for PingDirectory
  - target:
      group:
      version: v1
      kind: ConfigMap
      name: pingdirectory-environment-variables
    patch: |-
      - op: remove
        path: /data/SERVER_PROFILE_PATH
      - op: remove
        path: /data/SERVER_PROFILE_URL
  # Remove entries for profile URL and paths for PingFederate
  - target:
      group:
      version: v1
      kind: ConfigMap
      name: pingfederate-environment-variables
    patch: |-
      - op: remove
        path: /data/SERVER_PROFILE_PATH
      - op: remove
        path: /data/SERVER_PROFILE_URL
          # Remove entries for profile URL and paths for PingFederate
  # Remove entries for profile URL and paths for PingAccess
  - target:
      group:
      version: v1
      kind: ConfigMap
      name: pingaccess-environment-variables
    patch: |-
      - op: remove
        path: /data/SERVER_PROFILE_PATH
      - op: remove
        path: /data/SERVER_PROFILE_URL
  # Remove entries for profile URL and paths for pingaccess
  # Add the paths to the PingDirectory profile local folder
  - target:
      group:
      version: v1
      kind: PersistentVolume
      name: pd-profile-volume
    patch: |-
      - op: replace
        path: /spec/local/path
        value: /Users/ujwolshrestha/projects/devops/ping_kubernetes_playground/pingidentity-server-profiles/getting-started/pingdirectory
  # Add the paths to the PingFederate profile local folder
  - target:
      group:
      version: v1
      kind: PersistentVolume
      name: pf-profile-volume
    patch: |-
      - op: replace
        path: /spec/local/path
        value: /Users/ujwolshrestha/projects/devops/ping_kubernetes_playground/pingidentity-server-profiles/getting-started/pingfederate
  # Add the paths to the PingAccess profile local folder
  - target:
      group:
      version: v1
      kind: PersistentVolume
      name: pa-profile-volume
    patch: |-
      - op: replace
        path: /spec/local/path
        value: /Users/ujwolshrestha/projects/devops/ping_kubernetes_playground/pingidentity-server-profiles/getting-started/pingaccess
  # Insert claims and volumes for containers for the PingFederate profile
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: pingfederate
    patch: |-
      - op: add
        path: /spec/template/spec/volumes
        value: 
            - name: pf-profile-storage
              persistentVolumeClaim:
                claimName: pf-profile-claim
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts
        value: 
          - name: pf-profile-storage
            mountPath: /opt/in
  # Insert claims and volumes for containers for the PingDirectory profile
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: pingdirectory
    patch: |-
      - op: add
        path: /spec/template/spec/volumes
        value: 
            - name: pd-profile-storage
              persistentVolumeClaim:
                claimName: pd-profile-claim
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts
        value: 
            - mountPath: /opt/in
              name: pd-profile-storage
  # Insert claims and volumes for containers for the PingAccess profile
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: pingaccess
    patch: |-
      - op: add
        path: /spec/template/spec/volumes
        value: 
            - name: pa-profile-storage
              persistentVolumeClaim:
                claimName: pa-profile-claim
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts
        value: 
            - mountPath: /opt/in
              name: pa-profile-storage

